completed
js-tasks-ru/js-20220613_kabanova-karina pull request #2
Opened 2022-06-18 14:21 UTC by Karina1703

2022-06-18 14:22 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-06-19 08:02 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2022-06-19 12:14 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    let arrCopy = arr.slice()
более короткий и современный способ копировать массив:
```
const copy = [...arr]
```

2022-06-19 12:14 UTC, dosandk commented on 02-javascript-data-types/1-sort-strings/index.js
> +    if (param === 'desc') return arrCopy.reverse()
Подумайте как исправить решение таким образом чтобы избавиться от `reverse` и сортировать данные сразу в верном порядке

2022-06-19 12:14 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +    let object = {};
почему здесь `let`?

2022-06-19 12:15 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +    fields.map((item) => {
`map` применяется там где нужно вернуть новый массив после итерации, здесь же следует применить `for...of`

2022-06-19 12:16 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +        for (const [key, value] of Object.entries(obj)) {
подумайте что следует итерировать в первую очередь `fields` или `Object.entries`?

2022-06-19 12:16 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +                delete object[key]
использовать `delete` в связке с объектом не рекомендуется, мы изменим исходный объект `obj`

2022-06-19 12:17 UTC, dosandk requested changes
решение `sortStrings` следует поправить

2022-06-19 16:12 UTC, jsru commented
Добавляю преподавателя (@dosandk) для код-ревью.

2022-06-19 16:18 UTC, Karina1703 commented on 02-javascript-data-types/3-omit/index.js
> +                delete object[key]
а почему изменим исходынй объект? я ведь создала копию объекта на 8 строчке))

2022-06-19 16:28 UTC, Karina1703 commented on 02-javascript-data-types/3-omit/index.js
> +                delete object[key]
а, я поняла - я фактически передала ссылку на один и тот же объект, поэтому при вызовe delete я удаляю исходный объект?

2022-06-19 16:40 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @dosandk

2022-06-20 14:55 UTC, dosandk commented on 02-javascript-data-types/3-omit/index.js
> +                delete object[key]
да

2022-06-20 14:55 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +    var object = {};
откуда `var` взялся? неужели из 2014 года?

2022-06-20 14:55 UTC, dosandk commented on 02-javascript-data-types/2-pick/index.js
> +    let arrayFromObj = Object.entries(obj)
`const`

2022-06-20 14:56 UTC, dosandk approved these changes

2022-06-20 14:56 UTC, merged